spring:
  datasource:
    username: shuang
    password: mysql215311?
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations:
     classpath*:generator/*.xml
